
package TresEnRaya;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author ASUS VIVOBOOK
 */
public class ventanaInicial extends javax.swing.JFrame {

    private int b1,b2,b3,b4,b5,b6,b7,b8,b9;
    private int botonesDisponibles=9,g1=0,g2=0,e=0;
    private int jugador=1;
    private String nombre1,nombre2;
    private ventanaPrincipal vp=new ventanaPrincipal();
    
    
    /**
     * Creates new form ventanaInicial
     */

    public ventanaInicial(String nombre1,String nombre2){
        this.nombre1=nombre1;
        this.nombre2=nombre2;
        initComponents();
        setLocationRelativeTo(null);     
    }

    private void verificarGanador(){
        if(botonesDisponibles<5){
            if((b1==1 && b2==1 && b3==1) || (b4==1 && b5==1 && b6==1) || (b7==1 && b8==1 && b9==1) || 
                (b1==1 && b4==1 && b7==1) || (b2==1 && b5==1 && b8==1) || (b3==1 && b6==1 && b9==1) || 
                (b1==1 && b5==1 && b9==1) ||  (b3==1 && b5==1 && b7==1)){              
                g1++;
                ventanaGanador vg= new ventanaGanador(this,true,nombre1);
                vg.setVisible(true);      
                reiniciar();
            }
            else if((b1==2 && b2==2 && b3==2) || (b4==2 && b5==2 && b6==2) || (b7==2 && b8==2 && b9==2) || 
                (b1==2 && b4==2 && b7==2) || (b2==2 && b5==2 && b8==2) || (b3==2 && b6==2 && b9==2) || 
                (b1==2 && b5==2 && b9==2) ||  (b3==2 && b5==2 && b7==2)){
                g2++;
                ventanaGanador vg= new ventanaGanador(this,true,nombre2);
                vg.setVisible(true);      
                reiniciar();
            }
            else if(botonesDisponibles==0){
                e++;
                ventanaEmpate ve= new ventanaEmpate(this, true);
                ve.setVisible(true);
                reiniciar();
                
            }
        }
    }
    
    private void reiniciar(){  
        ventanaEscogerTurno vet=new ventanaEscogerTurno(this, true,nombre1,nombre2);       
        boton1.setIcon(null);      
        boton2.setIcon(null);
        boton3.setIcon(null);
        boton4.setIcon(null);
        boton5.setIcon(null);
        boton6.setIcon(null);
        boton7.setIcon(null);
        boton8.setIcon(null);
        boton9.setIcon(null);
        b1=0; b2=0;b3=0; b4=0; b5=0; b6=0; b7=0; b8=0; b9=0;
        botonesDisponibles=9;
        vet.setVisible(true);
        jugador= vet.getJugador();
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        barraMenu = new javax.swing.JMenuBar();
        menuJuego = new javax.swing.JMenu();
        itemJugarDeNuevo = new javax.swing.JMenuItem();
        itemHistorial = new javax.swing.JMenuItem();
        separador = new javax.swing.JPopupMenu.Separator();
        itemSalir = new javax.swing.JMenuItem();
        itemAyuda = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        boton1.setMaximumSize(new java.awt.Dimension(32, 32));
        boton1.setMinimumSize(new java.awt.Dimension(32, 32));
        boton1.setPreferredSize(new java.awt.Dimension(32, 32));
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton1, gridBagConstraints);

        boton2.setPreferredSize(new java.awt.Dimension(32, 32));
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton2, gridBagConstraints);

        boton3.setPreferredSize(new java.awt.Dimension(32, 32));
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton3, gridBagConstraints);

        boton4.setPreferredSize(new java.awt.Dimension(32, 32));
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton4, gridBagConstraints);

        boton5.setPreferredSize(new java.awt.Dimension(32, 32));
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton5, gridBagConstraints);

        boton6.setPreferredSize(new java.awt.Dimension(32, 32));
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton6, gridBagConstraints);

        boton7.setPreferredSize(new java.awt.Dimension(32, 32));
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton7, gridBagConstraints);

        boton8.setPreferredSize(new java.awt.Dimension(32, 32));
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton8, gridBagConstraints);

        boton9.setPreferredSize(new java.awt.Dimension(32, 32));
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel1.add(boton9, gridBagConstraints);

        menuJuego.setText("Juego");
        menuJuego.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        itemJugarDeNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        itemJugarDeNuevo.setText("Comenzar de nuevo");
        itemJugarDeNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemJugarDeNuevoActionPerformed(evt);
            }
        });
        menuJuego.add(itemJugarDeNuevo);

        itemHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/historial.png"))); // NOI18N
        itemHistorial.setText("Mostrar Resultados");
        itemHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHistorialActionPerformed(evt);
            }
        });
        menuJuego.add(itemHistorial);
        menuJuego.add(separador);

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar.png"))); // NOI18N
        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        menuJuego.add(itemSalir);

        barraMenu.add(menuJuego);

        itemAyuda.setText("Ayuda");
        itemAyuda.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        itemAyuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemAyudaMouseClicked(evt);
            }
        });
        itemAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAyudaActionPerformed(evt);
            }
        });
        barraMenu.add(itemAyuda);

        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        if(b1==0){
            if(jugador==1){
                boton1.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b1=1;
            }
            else {
                boton1.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b1=2;
            }
        botonesDisponibles--;
        verificarGanador();
        }
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
          if(b2==0){
            if(jugador==1){
                boton2.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b2=1;
            }
            else {
                boton2.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b2=2;
            }
        botonesDisponibles--;
        verificarGanador();
          }
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
        if(b3==0){
            if(jugador==1){
                boton3.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b3=1;
            }
            else {
                boton3.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b3=2;
            }
        botonesDisponibles--;
        verificarGanador();
        }
    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
        if(b4==0){
            if(jugador==1){
                boton4.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b4=1;
            }
            else {
                boton4.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b4=2;
            }
            botonesDisponibles--;
            verificarGanador();
          }
    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
        if(b5==0){
            if(jugador==1){
                boton5.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b5=1;
            }
            else {
                boton5.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b5=2;
            }
            botonesDisponibles--;
            verificarGanador();
        }
    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
        if(b6==0){
            if(jugador==1){
                boton6.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b6=1;
            }
            else {
                boton6.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b6=2;
            }
            botonesDisponibles--;
            verificarGanador();
        }
    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        if(b7==0){
            if(jugador==1){
                boton7.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b7=1;
            }
            else {
                boton7.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b7=2;
            }
            botonesDisponibles--;
            verificarGanador();
        }
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
        if(b8==0){
            if(jugador==1){
                boton8.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b8=1;
            }
            else {
                boton8.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b8=2;
            }
            botonesDisponibles--;
            verificarGanador();
        }
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
        if(b9==0){
            if(jugador==1){
                boton9.setIcon(new ImageIcon(getClass().getResource("/imagenes/x.png")));
                jugador=2;
                b9=1;
            }
            else {
                boton9.setIcon(new ImageIcon(getClass().getResource("/imagenes/o.png")));
                jugador=1;
                b9=2;
            }
            botonesDisponibles--;
            verificarGanador();
        }
    }//GEN-LAST:event_boton9ActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemJugarDeNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemJugarDeNuevoActionPerformed
        reiniciar();
        e=0;g1=0;g2=0;
    }//GEN-LAST:event_itemJugarDeNuevoActionPerformed

    private void itemHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHistorialActionPerformed
        ventanaHistorial vh= new ventanaHistorial(this, true,nombre1, nombre2, g1, g2, e);
        vh.setVisible(true);
    }//GEN-LAST:event_itemHistorialActionPerformed

    private void itemAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAyudaActionPerformed
        
    }//GEN-LAST:event_itemAyudaActionPerformed

    private void itemAyudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemAyudaMouseClicked
        try
        {
            Desktop.getDesktop().browse(new URI("https://www.guiainfantil.com/articulos/ocio/juegos/juego-de-tres-en-raya-como-jugar-con-los-ninos-con-papel-y-lapiz/"));
        } catch (URISyntaxException | IOException ex)
        {
            //Logger.getLogger(ventanaInicial.class.getName()).log(Level.SEVERE, null, ex);
        }     
    }//GEN-LAST:event_itemAyudaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ventanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ventanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ventanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ventanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ventanaInicial(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JMenu itemAyuda;
    private javax.swing.JMenuItem itemHistorial;
    private javax.swing.JMenuItem itemJugarDeNuevo;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menuJuego;
    private javax.swing.JPopupMenu.Separator separador;
    // End of variables declaration//GEN-END:variables
}
